---
all:
  hosts:
    aws_ec2:
      # --- GANTI INI DENGAN IP PUBLIC AWS EC2 ANDA BESOK ---
      ansible_host: 3.123.45.67 
      
      # User default untuk Amazon Linux 2 (JANGAN DIGANTI)
      ansible_user: ec2-user
      
      # Jenkins akan menyuntikkan SSH Key (.pem) saat runtime, 
      # jadi kita tidak perlu menuliskan jalur file .pem di sini.